window:
  title: ''
  dynamic_title: false
  opacity: 0.95
  padding:
    x: 8
    y: 8
  decorations: buttonless

tabspaces: 2

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic
  size: 14

draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: Q, mods: Control, chars: "\x11" }

mouse:
  hide_when_typing: true

schemes:
  tokyonight: &tokyonight
    # Default colors
    primary:
      background: '#1a1b26'
      foreground: '#a9b1d6'

    # Normal colors
    normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#787c99'

    # Bright colors
    bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'

  duskfox: &duskfox
    # Default colors
    primary:
      background: '#232136'
      foreground: '#e0def4'
    # Normal colors
    normal:
      black:   '#393552'
      red:     '#eb6f92'
      green:   '#a3be8c'
      yellow:  '#f6c177'
      blue:    '#569fba'
      magenta: '#c4a7e7'
      cyan:    '#9ccfd8'
      white:   '#e0def4'
    # Bright colors
    bright:
      black:   '#47407d'
      red:     '#f083a2'
      green:   '#b1d196'
      yellow:  '#f9cb8c'
      blue:    '#65b1cd'
      magenta: '#ccb1ed'
      cyan:    '#a6dae3'
      white:   '#e2e0f7'
    indexed_colors:
      - { index: 17, color: '#eb98c3' }

colors: *tokyonight
