window:
  title: ''
  dynamic_title: false
  opacity: 0.97
  padding:
    x: 8
    y: 8

tabspaces: 4

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic
  size: 13.0
  
draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: Q, mods: Control, chars: "\x11" }

schemes:
  deus: &deus
    # Default colors
    primary:
      background: '#2c323b'
      foreground: '#eaeaea'

    # Normal colors
    normal:
      black:   '#242a32'
      red:     '#d54e53'
      green:   '#98c379'
      yellow:  '#e5c07b'
      blue:    '#83a598'
      magenta: '#c678dd'
      cyan:    '#70c0ba'
      white:   '#eaeaea'
    
    # Bright colors
    bright:
      black:   '#666666'
      red:     '#ec3e45'
      green:   '#90c966'
      yellow:  '#edbf69'
      blue:    '#73ba9f'
      magenta: '#c858e9'
      cyan:    '#2bcec2'
      white:   '#ffffff'

colors: *deus
